[package]
name = "reader"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.1"
egui_commonmark = { version = "0.25.0", features = ["load-images"] }
egui_extras = { version = "0.36.1", features = ["file", "image"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"
