[target.x86_64-pc-windows-gnu]
linker = "D:/project/test/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin/rust-lld.exe"
rustflags = ["-C", "link-self-contained=yes"]
